### ISSUE TITLE
1.19.4 Issues with methods

### ISSUE THREAD

**Issue by Sean1472** [TheGaming999/BlockChanger#3]
Hello,

It seems it may not work on 1.19.4 no more.

Errors:
`java.lang.NoSuchMethodException: no such method: net.minecraft.world.level.block.Block.m()IBlockData/invokeVirtual`
`Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.IBlockData net.minecraft.world.level.block.Block.m()'`

Other errors:
`java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.invoke(Object)" because "me.sean0402.deluxemines.Blocks.BlockChanger.NMS_ITEM_STACK_TO_ITEM" is null`

**Comment by Sandwichas** [comment]
Just updated. Let me know if there is still any issue
